[toolchain]
channel = "1.89.0-nightly"
components = ["rustfmt", "clippy"]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter_dapp = "GXsxdre1jBvjT1R4fEZxPumaHzf5TnrMRpFx1MVGz4QV"

[programs.devnet]
counter_dapp = "GXsxdre1jBvjT1R4fEZxPumaHzf5TnrMRpFx1MVGz4QV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
package_manager = "npm"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"